name: Forward Release to Telegram

on:
  release:
    types:
      - created

jobs:
  forward-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip install requests

    - name: Forward Release to Telegram
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      run: |
        TAG_NAME=$(echo "${{ github.event.release.tag_name }}")
        RELEASE_NOTES=$(echo "${{ github.event.release.body }}")

        curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage \
          -d text="New release: ${TAG_NAME}\n\nRelease notes:\n${RELEASE_NOTES}"
