name: Update meta-core and go modules
on:
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Checkout submodules
        run: git submodule update --init --recursive --remote

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      
      - name: Download GeoIP Database
        run: |
          ./gradlew :core:downloadGeoipDatabase

      - name: Update Foss Gomod
        run: |
          cd ./core/src/foss/golang/
          go mod download
          go mod tidy

      - name: Update Main Gomod
        run: |
          cd ./core/src/main/golang/
          go mod download
          go mod tidy

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update Dependencies
          branch: update-dependencies
          delete-branch: true
          title: 'Update Dependencies'
          draft: false
          body: |
            Update Dependencies
            - Update Clash-Meta Core
            - Update Go Modules
          labels: |
            update
        
      - name: Create PR outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
      
